import type { NextPage } from 'next'
import dynamic from 'next/dynamic'
import Head from 'next/head'

const PhaserGame = dynamic(() => import('../phaser-game/PhaserGame'), {
  ssr: false,
})


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Zero First Game</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
        <div id="game">
          <PhaserGame />
        </div>
      </main>
    </div>
  )
}

export default Home
